In [1]:
import numpy as np

# Questions 1:
### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [7]:
arr=np.arange(2,51,3) # to include 50 in the output using STOP:51 
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Questions 2:
### Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [51]:
a=input("Please enter 5 values separated by , for List1")
lst1=[int(i) for i in a.split(",")]
b=input("Please enter 5 values separated by , for List2")
lst2=[int(i) for i in b.split(",")]
arr1=np.array(lst1)
arr2=np.array(lst2)
concarray=np.concatenate((arr1,arr2))
np.sort(concarray)

array([ 1, 21, 23, 23, 43, 55, 66, 85, 87, 88])

# Questions 3:
### Write a code snippet to find the dimensions of a ndarray and its size.


In [55]:
print(concarray.shape)
print(concarray.size)

(10,)
10


# Questions 4:
### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
### Hint: np.newaxis, np.expand_dims

In [89]:
arr1=np.array([2,3,4,1,5,7,8,6,3,4,1,23])
print("1D Array:",arr1.shape)
arr1=np.reshape(arr1,(3,4))
print("Converted it to 2D",arr1.shape)

1D Array: (12,)
Converted it to 2D (3, 4)


# Questions 5:
### Consider two square numpy arrays. Stack them vertically and horizontally.
### Hint: Use vstack(), hstack()

In [105]:
one=np.ones((3,3))
zero=np.zeros((3,3))
print("Vertically Stacking: ",np.vstack((one,zero)))
print("Horizontally Stacking: ",np.hstack((one,zero)))


Vertically Stacking:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Horizontally Stacking:  [[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


# Questions 6:
### How to get unique items and counts of unique items?

In [141]:
arr3=np.array([1,34,656,23,23,576,72,44,44])
#print("Unique Items in the Array: ",np.unique(arr3))
#print("Count of Unique item in Array",np.unique(arr3,return_counts=True)[1])
element,count=np.unique(arr3,return_counts=True)
print("\tElement","It's Count")
np.asarray((element,count)).T

	Element It's Count


array([[  1,   1],
       [ 23,   2],
       [ 34,   1],
       [ 44,   2],
       [ 72,   1],
       [576,   1],
       [656,   1]])